version: '3.9'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl_data:/etc/resty-auto-ssl
    environment:
      ALLOWED_DOMAINS: "${BACKEND_ALLOWED_DOMAINS}"
      SITES: "${BACKEND_ALLOWED_DOMAINS}=backend:80"
  
  db:
    image: postgres:latest
    volumes:
      - lct-hack-db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    ports:
      - ${BACKEND_PORT}80:${BACKEND_PORT}
    environment:
      DEBUG: ${DEBUG}

      BACKEND_TTILE: ${BACKEND_TTILE}
      BACKEND_DESCRIPTION: ${BACKEND_DESCRIPTION}
      BACKEND_PREFIX: ${BACKEND_PREFIX}

      BACKEND_HOST: ${BACKEND_HOST}
      BACKEND_PORT: ${BACKEND_PORT}
      BACKEND_RELOAD: ${BACKEND_RELOAD}

      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}

      BACKEND_JWT_SECRET: ${BACKEND_JWT_SECRET}
      BACKEND_JWT_ALGORITHM: ${BACKEND_JWT_ALGORITHM}
      BACKEND_JWT_ACCESS_TOKEN_EXPIRE_MINUTES: ${BACKEND_JWT_ACCESS_TOKEN_EXPIRE_MINUTES}

      BACKEND_DADATA_TOKEN: ${BACKEND_DADATA_TOKEN}

      BACKEND_DISABLE_AUTH: ${BACKEND_DISABLE_AUTH}
      BACKEND_DISABLE_FILE_SENDING: ${BACKEND_DISABLE_FILE_SENDING}

      STORAGE_REGION: ${STORAGE_REGION}
      STORAGE_ENDPOINT: ${STORAGE_ENDPOINT}
      STORAGE_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      STORAGE_ACCESS_KEY_ID: ${STORAGE_ACCESS_KEY_ID}
      STORAGE_BUCKET_NAME: ${STORAGE_BUCKET_NAME}
      STORAGE_FOLDER_NAME: ${STORAGE_FOLDER_NAME}

      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      ENV: development
  
  frontend:
    build:
      context: ./frontend
      environment:
        NEXT_APP_API_URL: ${NEXT_APP_API_URL}
        NEXT_APP_PARSER_API_URL: ${NEXT_APP_PARSER_API_URL}



volumes:
  lct-hack-db-data:
  ssl_data:
